package com.loganalyzer.models;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * Represents a support/incident ticket in the lifecycle management system.
 * Tracks full lifecycle from creation through resolution with SLA enforcement.
 */
public class Ticket {

    private static final DateTimeFormatter FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    private final String ticketId;
    private String title;
    private String description;
    private ErrorType issueType;
    private Priority priority;
    private TicketStatus status;
    private final LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private LocalDateTime resolvedAt;
    private LocalDateTime closedAt;
    private final LocalDateTime slaDeadline;
    private String assignedTo;
    private String sourceLogEntry; // Reference to originating log entry
    private String affectedEndpoint;
    private String affectedService;
    private final List<String> statusHistory;
    private String resolutionNotes;
    private boolean autoGenerated; // True if created from log analysis

    // ─── Constructor ───────────────────────────────────────────────────────────

    public Ticket(String title, ErrorType issueType, Priority priority) {
        this.ticketId = "TKT-" + UUID.randomUUID().toString().substring(0, 8).toUpperCase();
        this.title = title;
        this.issueType = issueType;
        this.priority = priority;
        this.status = TicketStatus.OPEN;
        this.createdAt = LocalDateTime.now();
        this.updatedAt = this.createdAt;
        this.slaDeadline = this.createdAt.plusHours(priority.getSlaHours());
        this.statusHistory = new ArrayList<>();
        this.statusHistory.add(String.format("[%s] Ticket created with status: OPEN",
                this.createdAt.format(FORMATTER)));
        this.autoGenerated = false;
    }

    // ─── Status Management ─────────────────────────────────────────────────────

    /**
     * Transitions the ticket to a new status if the transition is valid.
     *
     * @param newStatus the target status
     * @throws IllegalStateException if the transition is not allowed
     */
    public void transitionTo(TicketStatus newStatus) {
        if (!newStatus.isValidTransitionFrom(this.status)) {
            throw new IllegalStateException(
                    String.format("Invalid transition: %s -> %s", this.status, newStatus));
        }
        TicketStatus old = this.status;
        this.status = newStatus;
        this.updatedAt = LocalDateTime.now();
        statusHistory.add(String.format("[%s] Status changed: %s -> %s",
                this.updatedAt.format(FORMATTER), old, newStatus));

        if (newStatus == TicketStatus.RESOLVED) {
            this.resolvedAt = this.updatedAt;
        } else if (newStatus == TicketStatus.CLOSED) {
            this.closedAt = this.updatedAt;
            if (this.resolvedAt == null)
                this.resolvedAt = this.updatedAt;
        }
    }

    // ─── SLA Methods ───────────────────────────────────────────────────────────

    /**
     * Returns true if the SLA deadline has been breached.
     */
    public boolean isSlaBreached() {
        LocalDateTime referenceTime = resolvedAt != null ? resolvedAt : LocalDateTime.now();
        return referenceTime.isAfter(slaDeadline);
    }

    /**
     * Returns the time-to-resolution in minutes, or -1 if not yet resolved.
     */
    public long getTimeToResolutionMinutes() {
        if (resolvedAt == null)
            return -1;
        return ChronoUnit.MINUTES.between(createdAt, resolvedAt);
    }

    /**
     * Returns time remaining until SLA breach (negative if already breached).
     */
    public long getSlaRemainingMinutes() {
        LocalDateTime now = LocalDateTime.now();
        return ChronoUnit.MINUTES.between(now, slaDeadline);
    }

    /**
     * Returns how many minutes past the SLA deadline resolution occurred (0 if
     * within SLA).
     */
    public long getSlaBreachMinutes() {
        if (!isSlaBreached())
            return 0;
        LocalDateTime referenceTime = resolvedAt != null ? resolvedAt : LocalDateTime.now();
        return ChronoUnit.MINUTES.between(slaDeadline, referenceTime);
    }

    // ─── Display Methods ───────────────────────────────────────────────────────

    public String getSummaryLine() {
        String slaStatus = isSlaBreached() ? "⚠ SLA BREACHED" : "✓ Within SLA";
        return String.format("%-12s | %-8s | %-10s | %-16s | %s | %s",
                ticketId, priority.getDisplayName(), status.getDisplayName(),
                issueType.getDisplayName().substring(0, Math.min(16, issueType.getDisplayName().length())),
                slaStatus,
                createdAt.format(FORMATTER));
    }

    public String getDetailedView() {
        StringBuilder sb = new StringBuilder();
        sb.append("═".repeat(70)).append("\n");
        sb.append(String.format("  TICKET: %s%s\n", ticketId,
                autoGenerated ? " [AUTO-GENERATED]" : ""));
        sb.append("═".repeat(70)).append("\n");
        sb.append(String.format("  Title        : %s\n", title));
        sb.append(String.format("  Issue Type   : %s\n", issueType.getDisplayName()));
        sb.append(String.format("  Priority     : %s (SLA: %dh)\n",
                priority, priority.getSlaHours()));
        sb.append(String.format("  Status       : %s\n", status));
        if (assignedTo != null)
            sb.append(String.format("  Assigned To  : %s\n", assignedTo));
        if (affectedService != null)
            sb.append(String.format("  Service      : %s\n", affectedService));
        if (affectedEndpoint != null)
            sb.append(String.format("  Endpoint     : %s\n", affectedEndpoint));
        sb.append("─".repeat(70)).append("\n");
        sb.append(String.format("  Created At   : %s\n", createdAt.format(FORMATTER)));
        sb.append(String.format("  SLA Deadline : %s\n", slaDeadline.format(FORMATTER)));
        if (resolvedAt != null) {
            sb.append(String.format("  Resolved At  : %s\n", resolvedAt.format(FORMATTER)));
            sb.append(String.format("  Resolution   : %dm\n", getTimeToResolutionMinutes()));
        }
        sb.append(String.format("  SLA Status   : %s\n",
                isSlaBreached() ? "⚠ BREACHED by " + getSlaBreachMinutes() + "m" : "✓ Within SLA"));
        if (description != null) {
            sb.append("─".repeat(70)).append("\n");
            sb.append(String.format("  Description  : %s\n", description));
        }
        if (resolutionNotes != null) {
            sb.append(String.format("  Resolution   : %s\n", resolutionNotes));
        }
        sb.append("─".repeat(70)).append("\n");
        sb.append("  Status History:\n");
        statusHistory.forEach(h -> sb.append("    → ").append(h).append("\n"));
        sb.append("═".repeat(70)).append("\n");
        return sb.toString();
    }

    // ─── Getters & Setters ─────────────────────────────────────────────────────

    public String getTicketId() {
        return ticketId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public ErrorType getIssueType() {
        return issueType;
    }

    public void setIssueType(ErrorType issueType) {
        this.issueType = issueType;
    }

    public Priority getPriority() {
        return priority;
    }

    public void setPriority(Priority priority) {
        this.priority = priority;
    }

    public TicketStatus getStatus() {
        return status;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public LocalDateTime getResolvedAt() {
        return resolvedAt;
    }

    public LocalDateTime getClosedAt() {
        return closedAt;
    }

    public LocalDateTime getSlaDeadline() {
        return slaDeadline;
    }

    public String getAssignedTo() {
        return assignedTo;
    }

    public void setAssignedTo(String assignedTo) {
        this.assignedTo = assignedTo;
    }

    public String getSourceLogEntry() {
        return sourceLogEntry;
    }

    public void setSourceLogEntry(String sourceLogEntry) {
        this.sourceLogEntry = sourceLogEntry;
    }

    public String getAffectedEndpoint() {
        return affectedEndpoint;
    }

    public void setAffectedEndpoint(String affectedEndpoint) {
        this.affectedEndpoint = affectedEndpoint;
    }

    public String getAffectedService() {
        return affectedService;
    }

    public void setAffectedService(String affectedService) {
        this.affectedService = affectedService;
    }

    public List<String> getStatusHistory() {
        return statusHistory;
    }

    public String getResolutionNotes() {
        return resolutionNotes;
    }

    public void setResolutionNotes(String resolutionNotes) {
        this.resolutionNotes = resolutionNotes;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    @Override
    public String toString() {
        return String.format("Ticket[%s | %s | %s | %s]",
                ticketId, priority, status, issueType.getDisplayName());
    }
}
