package com.loganalyzer.services;

import com.loganalyzer.models.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.stream.Collectors;

/**
 * Service layer for managing the full lifecycle of incident tickets.
 * Supports creation, status transitions, priority updates, resolution tracking,
 * and querying tickets by various criteria.
 */
public class TicketService {

    private static final Logger logger = LoggerFactory.getLogger(TicketService.class);
    private static final DateTimeFormatter FMT = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    private final Map<String, Ticket> ticketStore = new LinkedHashMap<>();

    // ─── Ticket Creation ───────────────────────────────────────────────────────

    /**
     * Creates a new ticket with the given attributes.
     */
    public Ticket createTicket(String title, String description, ErrorType issueType, Priority priority) {
        Ticket ticket = new Ticket(title, issueType, priority);
        ticket.setDescription(description);
        ticketStore.put(ticket.getTicketId(), ticket);
        logger.info("Ticket created: {} [{}] priority={}", ticket.getTicketId(), issueType, priority);
        return ticket;
    }

    /**
     * Creates a ticket pre-populated from the given
     * {@link com.loganalyzer.models.LogEntry},
     * marking it as auto-generated from log analysis.
     */
    public Ticket createFromLogEntry(com.loganalyzer.models.LogEntry logEntry) {
        ErrorType type = logEntry.getDetectedErrorType() != null
                ? logEntry.getDetectedErrorType()
                : ErrorType.UNKNOWN;
        Priority priority = type.getDefaultPriority();

        String title = buildTitle(type, logEntry);
        Ticket ticket = new Ticket(title, type, priority);
        ticket.setDescription(buildDescription(logEntry));
        ticket.setAutoGenerated(true);
        ticket.setSourceLogEntry(logEntry.getFormattedTimestamp() + " | " + logEntry.getMessage());
        if (logEntry.getEndpoint() != null)
            ticket.setAffectedEndpoint(logEntry.getEndpoint());
        if (logEntry.getServiceName() != null)
            ticket.setAffectedService(logEntry.getServiceName());

        ticketStore.put(ticket.getTicketId(), ticket);
        logger.info("Auto-ticket created: {} from log error [{}]", ticket.getTicketId(), type);
        return ticket;
    }

    // ─── Ticket Updates ─────────────────────────────────────────────────────────

    /**
     * Transitions a ticket's status. Validates the transition before applying.
     */
    public void updateStatus(String ticketId, TicketStatus newStatus) {
        Ticket ticket = getOrThrow(ticketId);
        ticket.transitionTo(newStatus);
        logger.info("Ticket {} status updated to {}", ticketId, newStatus);
    }

    /**
     * Updates the priority of an open or in-progress ticket.
     */
    public void updatePriority(String ticketId, Priority newPriority) {
        Ticket ticket = getOrThrow(ticketId);
        if (ticket.getStatus().isTerminal()) {
            throw new IllegalStateException("Cannot update priority of a terminal ticket: " + ticketId);
        }
        Priority old = ticket.getPriority();
        ticket.setPriority(newPriority);
        logger.info("Ticket {} priority changed: {} -> {}", ticketId, old, newPriority);
    }

    /**
     * Assigns the ticket to an engineer.
     */
    public void assignTicket(String ticketId, String assignee) {
        Ticket ticket = getOrThrow(ticketId);
        ticket.setAssignedTo(assignee);
        if (ticket.getStatus() == TicketStatus.OPEN) {
            ticket.transitionTo(TicketStatus.IN_PROGRESS);
        }
        logger.info("Ticket {} assigned to {}", ticketId, assignee);
    }

    /**
     * Resolves a ticket with optional resolution notes.
     */
    public void resolveTicket(String ticketId, String resolutionNotes) {
        Ticket ticket = getOrThrow(ticketId);
        ticket.setResolutionNotes(resolutionNotes);
        if (ticket.getStatus() == TicketStatus.IN_PROGRESS || ticket.getStatus() == TicketStatus.OPEN) {
            ticket.transitionTo(TicketStatus.RESOLVED);
        }
        logger.info("Ticket {} resolved. SLA breached: {}", ticketId, ticket.isSlaBreached());
    }

    /**
     * Closes a resolved ticket.
     */
    public void closeTicket(String ticketId) {
        Ticket ticket = getOrThrow(ticketId);
        ticket.transitionTo(TicketStatus.CLOSED);
        logger.info("Ticket {} closed", ticketId);
    }

    // ─── Querying ──────────────────────────────────────────────────────────────

    public Optional<Ticket> findById(String ticketId) {
        return Optional.ofNullable(ticketStore.get(ticketId));
    }

    public List<Ticket> getAllTickets() {
        return new ArrayList<>(ticketStore.values());
    }

    public List<Ticket> getTicketsByStatus(TicketStatus status) {
        return ticketStore.values().stream()
                .filter(t -> t.getStatus() == status)
                .collect(Collectors.toList());
    }

    public List<Ticket> getTicketsByPriority(Priority priority) {
        return ticketStore.values().stream()
                .filter(t -> t.getPriority() == priority)
                .collect(Collectors.toList());
    }

    public List<Ticket> getSlaBreachedTickets() {
        return ticketStore.values().stream()
                .filter(Ticket::isSlaBreached)
                .collect(Collectors.toList());
    }

    public List<Ticket> getOpenCriticalTickets() {
        return ticketStore.values().stream()
                .filter(t -> t.getPriority() == Priority.CRITICAL && !t.getStatus().isTerminal())
                .collect(Collectors.toList());
    }

    public List<Ticket> getAutoGeneratedTickets() {
        return ticketStore.values().stream()
                .filter(Ticket::isAutoGenerated)
                .collect(Collectors.toList());
    }

    public int getTotalCount() {
        return ticketStore.size();
    }

    public boolean isEmpty() {
        return ticketStore.isEmpty();
    }

    private Ticket getOrThrow(String ticketId) {
        return Optional.ofNullable(ticketStore.get(ticketId))
                .orElseThrow(() -> new NoSuchElementException("Ticket not found: " + ticketId));
    }

    // ─── Title / Description Builders ─────────────────────────────────────────

    private String buildTitle(ErrorType type, com.loganalyzer.models.LogEntry entry) {
        String endpoint = entry.getEndpoint() != null ? " [" + entry.getEndpoint() + "]" : "";
        return type.getDisplayName() + endpoint;
    }

    private String buildDescription(com.loganalyzer.models.LogEntry entry) {
        return String.format(
                "Auto-generated from log analysis.%n" +
                        "Timestamp  : %s%n" +
                        "Error Type : %s%n" +
                        "Message    : %s%n" +
                        "Root Cause : %s",
                entry.getFormattedTimestamp(),
                entry.getDetectedErrorType() != null ? entry.getDetectedErrorType().getDisplayName() : "Unknown",
                entry.getMessage() != null ? entry.getMessage() : "N/A",
                entry.getDetectedErrorType() != null ? entry.getDetectedErrorType().getRootCauseDescription() : "N/A");
    }
}
