package com.loganalyzer;

import com.loganalyzer.models.*;
import com.loganalyzer.services.*;
import com.loganalyzer.sla.*;

import java.nio.file.Paths;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * Standalone functional smoke test - runs without JUnit, validates all pipeline
 * stages.
 * Returns exit code 0 = all passed, 1 = failures.
 */
public class SmokeTestRunner {

    static int passed = 0;
    static int failed = 0;

    public static void main(String[] args) throws Exception {
        System.out.println("=== SMOKE TEST: Java REST API Log Analyzer & SLA Ticket Simulator ===");
        System.out.println("Running from: " + Paths.get("").toAbsolutePath());
        System.out.println();

        LogAnalyzerService analyzer = new LogAnalyzerService();
        TicketService ticketService = new TicketService();
        SlaComplianceEngine slaEngine = new SlaComplianceEngine();
        IncidentManagementService incidentService = new IncidentManagementService(analyzer, ticketService, slaEngine);

        // Test 1: JSON log parsing
        analyzer.analyze(Paths.get("sample_logs/api_logs.json"));
        check("JSON log parsing - entries > 0", analyzer.getTotalEntries() > 0);
        check("JSON log parsing - errors > 0", analyzer.getTotalErrors() > 0);
        int jsonEntries = analyzer.getTotalEntries();
        int jsonErrors = analyzer.getTotalErrors();
        System.out.printf("  Details: %d total entries, %d errors detected%n", jsonEntries, jsonErrors);

        // Test 2: Root cause classification
        boolean allClassified = analyzer.getErrorEntries().stream()
                .allMatch(e -> e.getDetectedErrorType() != null);
        check("All errors classified by RootCauseClassifier", allClassified);

        // Test 3: Error frequency aggregation
        var freq = analyzer.getErrorFrequency();
        check("Error frequency aggregation non-empty", !freq.isEmpty());
        System.out.print("  Error types detected: ");
        freq.forEach((t, c) -> System.out.print(t.getDisplayName().split(" ")[0] + "(" + c + ") "));
        System.out.println();

        // Test 4: Date grouping
        var byDate = analyzer.getErrorsByDate();
        check("Errors by date grouping works", !byDate.isEmpty());

        // Test 5: Auto-ticket generation
        List<Ticket> tickets = incidentService.generateTicketsFromLogs();
        check("Auto-ticket generation - tickets created", !tickets.isEmpty());
        check("Each ticket has valid ID", tickets.stream().allMatch(t -> t.getTicketId().startsWith("TKT-")));
        check("Each ticket has priority", tickets.stream().allMatch(t -> t.getPriority() != null));
        check("Tickets marked auto-generated", tickets.stream().allMatch(Ticket::isAutoGenerated));
        System.out.printf("  Created %d tickets from %d error types%n", tickets.size(), freq.size());

        // Test 6: SLA evaluation
        SlaComplianceEngine.SlaReport slaReport = slaEngine.evaluate(ticketService.getAllTickets());
        check("SLA evaluates all generated tickets", slaReport.totalTickets == tickets.size());
        check("Compliance rate in valid range", slaReport.complianceRate >= 0 && slaReport.complianceRate <= 100);
        check("SLA stats by priority populated", !slaReport.statsByPriority.isEmpty());
        System.out.printf("  SLA: %d tickets, %.1f%% compliance%n", slaReport.totalTickets, slaReport.complianceRate);

        // Test 7: Incident summary report
        String report = incidentService.generateIncidentSummaryReport();
        check("Incident report contains header", report.contains("UNIFIED INCIDENT SUMMARY"));
        check("Incident report contains ticket section", report.contains("TICKET STATUS SUMMARY"));
        check("Incident report contains SLA section", report.contains("SLA COMPLIANCE"));

        // Test 8: Plain-text log parsing
        LogAnalyzerService analyzer2 = new LogAnalyzerService();
        analyzer2.analyze(Paths.get("sample_logs/application.log"));
        check("Plain-text logs parsed", analyzer2.getTotalEntries() > 0);
        check("Plain-text errors detected", analyzer2.getTotalErrors() > 0);
        System.out.printf("  Plain-text: %d entries, %d errors%n", analyzer2.getTotalEntries(),
                analyzer2.getTotalErrors());

        // Test 9: DB error classification
        LogAnalyzerService analyzer3 = new LogAnalyzerService();
        analyzer3.analyze(Paths.get("sample_logs/db_errors.json"));
        long dbErrors = analyzer3.getErrorEntries().stream()
                .filter(e -> e.getDetectedErrorType() != null && e.getDetectedErrorType().isDatabaseError())
                .count();
        check("DB errors correctly classified (>= 3)", dbErrors >= 3);
        System.out.printf("  DB error log: %d database errors classified%n", dbErrors);

        // Test 10: Ticket lifecycle
        Ticket t = ticketService.createTicket("Test ticket", "desc",
                ErrorType.HTTP_500_INTERNAL_SERVER_ERROR, Priority.HIGH);
        check("Ticket starts OPEN", t.getStatus() == TicketStatus.OPEN);
        t.transitionTo(TicketStatus.IN_PROGRESS);
        check("Ticket transitions to IN_PROGRESS", t.getStatus() == TicketStatus.IN_PROGRESS);
        ticketService.resolveTicket(t.getTicketId(), "Fixed it");
        check("Ticket resolves correctly", ticketService.findById(t.getTicketId())
                .map(tk -> tk.getStatus() == TicketStatus.RESOLVED).orElse(false));
        check("Resolved ticket has timestamp", t.getResolvedAt() != null);

        // Test 11: SLA breach detection
        Ticket fresh = ticketService.createTicket("CRIT", "desc",
                ErrorType.DB_CONNECTION_FAILURE, Priority.CRITICAL);
        check("Fresh CRITICAL ticket not breached", !fresh.isSlaBreached());
        check("SLA remaining > 0", fresh.getSlaRemainingMinutes() > 0);

        // Summary
        System.out.println();
        System.out.println("─".repeat(55));
        System.out.printf("  RESULTS: %d passed, %d failed%n", passed, failed);
        System.out.println("─".repeat(55));

        if (failed == 0) {
            System.out.println("  ✓ ALL SMOKE TESTS PASSED");
        } else {
            System.out.println("  ✗ SOME TESTS FAILED - see above");
        }

        // Print sample report section
        System.out.println("\n" + "=".repeat(55));
        System.out.println("  SAMPLE OUTPUT: Incident Report Excerpt");
        System.out.println("=".repeat(55));
        System.out.println(report.substring(0, Math.min(1000, report.length())) + "...");

        System.exit(failed > 0 ? 1 : 0);
    }

    static void check(String label, boolean condition) {
        if (condition) {
            System.out.printf("  ✓ %s%n", label);
            passed++;
        } else {
            System.out.printf("  ✗ FAIL: %s%n", label);
            failed++;
        }
    }
}
